name: ğŸƒâ€â™‚pnpm

on:
  push:

jobs:
  pnpm_install:
    runs-on: ubuntu-22.04
    steps:
      - name: ã‚³ãƒ¼ãƒ‰ã‚’ãƒã‚§ãƒƒã‚¯ã‚¢ã‚¦ãƒˆã™ã‚‹
        uses: actions/checkout@v4.1.5
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.4
      - name: Node.js ã®ã‚»ãƒƒãƒˆã‚¢ãƒƒãƒ—ã‚’è¡Œã†
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - name: Node ã®ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ã™ã‚‹
        run: |
          pnpm install
